server:
  port: 9194
eureka:
  instance:
    hostname: neac_discovery_server
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone : http://${eureka.instance.hostname}:9192/eureka
      defaultZone : http://localhost:9192/eureka

app:
  environment: qa

