server:
  port: 9194
eureka:
  instance:
    hostname: neac_discovery_server
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone : http://${eureka.instance.hostname}:9192/eureka
      defaultZone : http://localhost:9192/eureka

# Add the kafka default configuration for bus enabled
# Messages 

app:
  environment: default - local env2  
spring:
    cloud:
      bus:
        trace:
          enabled: true
        refresh:
          enabled: true
        env:
          enabled: true
      stream:
        kafka:
          binder:
            brokers:
              - http://localhost:9092
              - http://localhost:9094
              - http://localhost:9096


management:
  endpoints:
    web:
      exposure:
        include: "*"
